coverage:
  status:
    project:
      default:
        target: 65%
        threshold: 10%
        only_pulls: true
ignore:
  - "test"
  - "internal/client-go"
  - "internal/clihelpers"
  - "internal/httpclient"
  - "internal/settingshelpers"
  - "internal/registrationhelpers"
  - "internal/testhelpers"
  - "docs"
  - "contrib"
  - "gen"
